//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixApp.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of attempts has been exhausted, restart the program and try again..
        /// </summary>
        internal static string AttemptsExhaustedError {
            get {
                return ResourceManager.GetString("AttemptsExhaustedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of columns in matrix: .
        /// </summary>
        internal static string InputColumns {
            get {
                return ResourceManager.GetString("InputColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of rows in matrix: .
        /// </summary>
        internal static string InputRows {
            get {
                return ResourceManager.GetString("InputRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number that is greater than or equal to 1 and less than or equal to 2 146 435 071. Try again..
        /// </summary>
        internal static string NotNumberError {
            get {
                return ResourceManager.GetString("NotNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snake style of this matrix
        ///{0}.
        /// </summary>
        internal static string SnakeStyle {
            get {
                return ResourceManager.GetString("SnakeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace = {0}.
        /// </summary>
        internal static string TraceResult {
            get {
                return ResourceManager.GetString("TraceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrixTraceApp allows you to create a matrix of specified dimensions and calculate its trace. The program was developed by Alexander Popov in 2021 using c# for free use. (©)
        ///.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unacceptabel value. Minimal dimension of matrix is 1x1. Try again..
        /// </summary>
        internal static string WrongDimensionerror {
            get {
                return ResourceManager.GetString("WrongDimensionerror", resourceCulture);
            }
        }
    }
}
